/// <reference types="cypress" />

Cypress.on("uncaught:exception", (err, runnable) => {
  // returning false here prevents Cypress from
  // failing the test
  return false;
});

import { validateObj } from "../../../functions/handle/handle";

const EverythingCollectionType = {
  docId: "q69BDFcDS7EDuG79Bq5r",
  name: "Everything",
  lastIndex: 0,
  fields: [
    { isDefault: true, type: "date", displayOnTable: true, id: "createdAt" },
    { id: "modifiedAt", displayOnTable: true, isDefault: true, type: "date" },
    { type: "string", isDefault: true, displayOnTable: true, id: "docId" },
    {
      type: "password",
      relatedCollectionTypeDocId: "",
      displayOnTable: true,
      enumOptions: [],
      mediaSingle: false,
      stringLong: false,
      id: "password",
      relationOneToOne: true,
      collectionFields: [],
    },
    {
      enumOptions: [],
      relatedCollectionTypeDocId: "",
      id: "String",
      stringLong: false,
      collectionFields: [],
      type: "string",
      mediaSingle: false,
      relationOneToOne: true,
      displayOnTable: true,
    },
    {
      stringLong: false,
      type: "number",
      relatedCollectionTypeDocId: "",
      mediaSingle: false,
      id: "Number",
      relationOneToOne: true,
      collectionFields: [],
      enumOptions: [],
      displayOnTable: true,
    },
    {
      mediaSingle: false,
      type: "map",
      enumOptions: [],
      stringLong: false,
      relatedCollectionTypeDocId: "",
      displayOnTable: true,
      collectionFields: [],
      relationOneToOne: true,
      id: "Map",
    },
    {
      type: "array",
      displayOnTable: true,
      stringLong: false,
      mediaSingle: false,
      relationOneToOne: true,
      relatedCollectionTypeDocId: "",
      collectionFields: [],
      id: "Array",
      enumOptions: [],
    },
    {
      relatedCollectionTypeDocId: "",
      id: "Boolean",
      mediaSingle: false,
      collectionFields: [],
      displayOnTable: true,
      stringLong: false,
      type: "boolean",
      enumOptions: [],
      relationOneToOne: true,
    },
    {
      stringLong: false,
      mediaSingle: false,
      collectionFields: [],
      displayOnTable: true,
      id: "Date",
      type: "date",
      relatedCollectionTypeDocId: "",
      relationOneToOne: true,
      enumOptions: [],
    },
    {
      relationOneToOne: true,
      enumOptions: [],
      relatedCollectionTypeDocId: "",
      type: "media",
      id: "Media multiple",
      displayOnTable: true,
      mediaSingle: false,
      collectionFields: [],
      stringLong: false,
    },
    {
      collectionFields: [],
      id: "Media single",
      stringLong: false,
      enumOptions: [],
      relationOneToOne: true,
      type: "media",
      mediaSingle: true,
      displayOnTable: true,
      relatedCollectionTypeDocId: "",
    },
    {
      id: "Rich text",
      stringLong: false,
      mediaSingle: false,
      collectionFields: [],
      displayOnTable: true,
      relatedCollectionTypeDocId: "",
      relationOneToOne: true,
      type: "rich-text",
      enumOptions: [],
    },
    {
      enumOptions: [],
      stringLong: false,
      displayOnTable: true,
      relationOneToOne: true,
      collectionFields: [],
      relatedCollectionTypeDocId: "",
      mediaSingle: false,
      type: "json",
      id: "json",
    },
    {
      relatedCollectionTypeDocId: "",
      collectionFields: [],
      enumOptions: ["Option1 ", "Optin2", "Option "],
      stringLong: false,
      type: "enum",
      displayOnTable: true,
      relationOneToOne: true,
      id: "Enum",
      mediaSingle: false,
    },
    {
      collectionFields: [],
      type: "relation",
      relationOneToOne: true,
      stringLong: false,
      mediaSingle: false,
      displayOnTable: true,
      relatedCollectionTypeDocId: "SXiPKTvARjaQBSbBtpxQ",
      id: "relation one to one",
      enumOptions: [],
    },
    {
      mediaSingle: false,
      id: "relation one to many",
      stringLong: false,
      relatedCollectionTypeDocId: "SXiPKTvARjaQBSbBtpxQ",
      displayOnTable: true,
      relationOneToOne: false,
      enumOptions: [],
      type: "relation",
      collectionFields: [],
    },
    {
      stringLong: false,
      type: "collection",
      enumOptions: [],
      relationOneToOne: true,
      collectionFields: [
        {
          id: "Something 1",
          relationOneToOne: true,
          stringLong: false,
          relatedCollectionTypeDocId: "",
          enumOptions: [],
          mediaSingle: false,
          collectionFields: [],
          type: "string",
          displayOnTable: true,
        },
        {
          relatedCollectionTypeDocId: "",
          displayOnTable: true,
          id: "Nuiber 1",
          collectionFields: [],
          type: "number",
          stringLong: false,
          enumOptions: [],
          mediaSingle: false,
          relationOneToOne: true,
        },
      ],
      id: "Subcollection",
      displayOnTable: true,
      relatedCollectionTypeDocId: "",
      mediaSingle: false,
    },
  ],
  draftable: true,
  size: 4,
  id: "everything",
  single: false,
};

const ValidDocument = {
  Array: ["apple", "banana", "orange"],
  String: "string",
  createdAt: "2021-11-06T12:43:34.527Z",
  modifiedAt: "2021-11-06T12:43:34.527Z",
  Number: 123,
  Subcollection: [
    {
      "Nuiber 1": 1342,
      "Something 1": "asdad asd a",
    },
    {
      "Something 1": "sadas",
      "Nuiber 1": 213,
    },
    {
      "Nuiber 1": 1324,
      "Something 1": "zxcz",
    },
  ],
  docId: "NC6dk0skpcqCYFRyrBRl",
  "relation one to many": [
    "12HEfjRIPmyuqsJHearE",
    "pfPlbwcUjZGkM3mdrOp1",
    "SM943x3ODrYQ0a5Ry0aQ",
    "TJBN3VX370zboFVpWGNT",
    "uq8yuKexBemPHEVb5TPr",
    "CquA4F6JCuaksgGi5jwA",
    "8kneY2UyjEdPjN7kdrL8",
    "QZ9jqn232HDJhg7tHDPe",
    "UuGIdWhiWTIe3GEAWaY8",
  ],
  Date: "2021-11-18",
  json: {
    banana: {
      color: "yellow",
    },
    apple: {
      color: "green",
    },
  },
  "Media multiple": [
    "https://firebasestorage.googleapis.com/v0/b/fireck-4c36e.appspot.com/o/htQYLmYJXQ7HxDPg7KNgW3.png?alt=media&token=1e390a5d-fc3a-44ea-ada6-3d93b47a338c",
    "https://firebasestorage.googleapis.com/v0/b/fireck-4c36e.appspot.com/o/2e0023dd-f70c-4753-aaba-9d37a5b8d08f.pdf?alt=media&token=5afc4974-4592-4458-a9bf-df321215a538",
    "https://firebasestorage.googleapis.com/v0/b/fireck-4c36e.appspot.com/o/6288b324-241f-48db-a13c-8f9fa5896b6c.mdzip?alt=media&token=ec2ae5a4-8b8a-4134-9430-4f26fa3b0b95",
    "https://firebasestorage.googleapis.com/v0/b/fireck-4c36e.appspot.com/o/f547ca3b-4442-48a5-8309-5950fa47b46b.pdf?alt=media&token=cab74d09-2515-4d54-b5f7-5976ca105faf",
    "https://firebasestorage.googleapis.com/v0/b/fireck-4c36e.appspot.com/o/81da7192-3093-4e0e-8ae9-5ea3b60be3cc.pdf?alt=media&token=5d772f47-5d54-4a81-ab2f-4bf78003d66d",
  ],
  Map: {
    apple: {
      color: "green",
    },
    banana: {
      color: "yellow",
    },
  },
  "Media single":
    "https://firebasestorage.googleapis.com/v0/b/fireck-4c36e.appspot.com/o/htQYLmYJXQ7HxDPg7KNgW3.png?alt=media&token=1e390a5d-fc3a-44ea-ada6-3d93b47a338c",
  "relation one to one": "12HEfjRIPmyuqsJHearE",
  Boolean: true,
  password: "password",
  Enum: "Option1 ",
};

describe("Server side data validation", () => {
  it("Completely valid document", () => {
    expect(validateObj(EverythingCollectionType.fields, ValidDocument)).to.deep.equal(
      ValidDocument
    );
  });
});
